class InnerFailure(BaseException):
    pass


class ProviderFailure(BaseException):
    pass
